# Generated by Django 4.2.7 on 2023-11-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='furniture',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
