# Generated by Django 4.2.7 on 2023-11-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_on',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='img',
        ),
    ]
